// @ts-nocheck
import type { MessageMethod } from './message';
import type { NotificationMethod } from './notification';
import type { ModalMethod } from './modal';
import type { DrawerMethod } from './drawer';

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		FkAffix: typeof import('@erp/common')['Affix'];
		FkAlert: typeof import('@erp/common')['Alert'];
		FkAnchor: typeof import('@erp/common')['Anchor'];
		FkAnchorLink: typeof import('@erp/common')['AnchorLink'];
		FkAutoComplete: typeof import('@erp/common')['AutoComplete'];
		FkAvatar: typeof import('@erp/common')['Avatar'];
		FkAvatarGroup: typeof import('@erp/common')['AvatarGroup'];
		FkBackTop: typeof import('@erp/common')['BackTop'];
		FkBadge: typeof import('@erp/common')['Badge'];
		FkBreadcrumb: typeof import('@erp/common')['Breadcrumb'];
		FkBreadcrumbItem: typeof import('@erp/common')['BreadcrumbItem'];
		FkButton: typeof import('@erp/common')['Button'];
		FkButtonGroup: typeof import('@erp/common')['ButtonGroup'];
		FkCalendar: typeof import('@erp/common')['Calendar'];
		FkCard: typeof import('@erp/common')['Card'];
		FkCardMeta: typeof import('@erp/common')['CardMeta'];
		FkCardGrid: typeof import('@erp/common')['CardGrid'];
		// FkCarousel: typeof import('@erp/common')['Carousel'];
		// FkCarouselItem: typeof import('@erp/common')['CarouselItem'];
		FkCascader: typeof import('@erp/common')['Cascader'];
		FkCascaderPanel: typeof import('@erp/common')['CascaderPanel'];
		FkCheckbox: typeof import('@erp/common')['Checkbox'];
		FkCheckboxGroup: typeof import('@erp/common')['CheckboxGroup'];
		FkCollapse: typeof import('@erp/common')['Collapse'];
		FkCollapseItem: typeof import('@erp/common')['CollapseItem'];
		FkColorPicker: typeof import('@erp/common')['ColorPicker'];
		FkComment: typeof import('@erp/common')['Comment'];
		FkConfigProvider: typeof import('@erp/common')['ConfigProvider'];
		FkDatePicker: typeof import('@erp/common')['DatePicker'];
		FkWeekPicker: typeof import('@erp/common')['WeekPicker'];
		FkMonthPicker: typeof import('@erp/common')['MonthPicker'];
		FkYearPicker: typeof import('@erp/common')['YearPicker'];
		FkQuarterPicker: typeof import('@erp/common')['QuarterPicker'];
		FkRangePicker: typeof import('@erp/common')['RangePicker'];
		FkDescriptions: typeof import('@erp/common')['Descriptions'];
		FkDescriptionsItem: typeof import('@erp/common')['DescriptionsItem'];
		FkDivider: typeof import('@erp/common')['Divider'];
		FkDrawer: typeof import('@erp/common')['Drawer'];
		FkDropdown: typeof import('@erp/common')['Dropdown'];
		FkDoption: typeof import('@erp/common')['Doption'];
		FkDgroup: typeof import('@erp/common')['Dgroup'];
		FkDsubmenu: typeof import('@erp/common')['Dsubmenu'];
		FkEmpty: typeof import('@erp/common')['Empty'];
		FkForm: typeof import('@erp/common')['Form'];
		FkFormItem: typeof import('@erp/common')['FormItem'];
		FkGrid: typeof import('@erp/common')['Grid'];
		FkGridItem: typeof import('@erp/common')['GridItem'];
		FkCol: typeof import('@erp/common')['Col'];
		FkRow: typeof import('@erp/common')['Row'];
		FkImage: typeof import('@erp/common')['Image'];
		FkImagePreview: typeof import('@erp/common')['ImagePreview'];
		FkImagePreviewAction: typeof import('@erp/common')['ImagePreviewAction'];
		FkImagePreviewGroup: typeof import('@erp/common')['ImagePreviewGroup'];
		FkInput: typeof import('@erp/common')['Input'];
		FkInputGroup: typeof import('@erp/common')['InputGroup'];
		FkInputSearch: typeof import('@erp/common')['InputSearch'];
		FkInputPassword: typeof import('@erp/common')['InputPassword'];
		FkInputNumber: typeof import('@erp/common')['InputNumber'];
		FkInputTag: typeof import('@erp/common')['InputTag'];
		FkLayout: typeof import('@erp/common')['Layout'];
		FkLayoutHeader: typeof import('@erp/common')['LayoutHeader'];
		FkLayoutContent: typeof import('@erp/common')['LayoutContent'];
		FkLayoutFooter: typeof import('@erp/common')['LayoutFooter'];
		FkLayoutSider: typeof import('@erp/common')['LayoutSider'];
		FkLink: typeof import('@erp/common')['Link'];
		FkList: typeof import('@erp/common')['List'];
		FkListItem: typeof import('@erp/common')['ListItem'];
		FkListItemMeta: typeof import('@erp/common')['ListItemMeta'];
		FkMention: typeof import('@erp/common')['Mention'];
		FkMenu: typeof import('@erp/common')['Menu'];
		FkMenuItem: typeof import('@erp/common')['MenuItem'];
		FkMenuItemGroup: typeof import('@erp/common')['MenuItemGroup'];
		FkSubMenu: typeof import('@erp/common')['SubMenu'];
		FkModal: typeof import('@erp/common')['Modal'];
		FkPageHeader: typeof import('@erp/common')['PageHeader'];
		FkPagination: typeof import('@erp/common')['Pagination'];
		FkPopconfirm: typeof import('@erp/common')['Popconfirm'];
		FkPopover: typeof import('@erp/common')['Popover'];
		FkProgress: typeof import('@erp/common')['Progress'];
		FkRadio: typeof import('@erp/common')['Radio'];
		FkRadioGroup: typeof import('@erp/common')['RadioGroup'];
		FkRate: typeof import('@erp/common')['Rate'];
		FkResizeBox: typeof import('@erp/common')['ResizeBox'];
		FkResult: typeof import('@erp/common')['Result'];
		FkSelect: typeof import('@erp/common')['Select'];
		FkOption: typeof import('@erp/common')['Option'];
		FkOptgroup: typeof import('@erp/common')['Optgroup'];
		FkSkeleton: typeof import('@erp/common')['Skeleton'];
		FkSkeletonLine: typeof import('@erp/common')['SkeletonLine'];
		FkSkeletonShape: typeof import('@erp/common')['SkeletonShape'];
		FkSlider: typeof import('@erp/common')['Slider'];
		FkSpace: typeof import('@erp/common')['Space'];
		FkSpin: typeof import('@erp/common')['Spin'];
		FkSplit: typeof import('@erp/common')['Split'];
		FkStatistic: typeof import('@erp/common')['Statistic'];
		FkCountdown: typeof import('@erp/common')['Countdown'];
		FkSteps: typeof import('@erp/common')['Steps'];
		FkStep: typeof import('@erp/common')['Step'];
		FkSwitch: typeof import('@erp/common')['Switch'];
		FkThead: typeof import('@erp/common')['Thead'];
		FkTd: typeof import('@erp/common')['Td'];
		FkTh: typeof import('@erp/common')['Th'];
		FkTr: typeof import('@erp/common')['Tr'];
		FkTbody: typeof import('@erp/common')['Tbody'];
		FkTableColumn: typeof import('@erp/common')['TableColumn'];
		FkTabs: typeof import('@erp/common')['Tabs'];
		FkTabPane: typeof import('@erp/common')['TabPane'];
		FkTag: typeof import('@erp/common')['Tag'];
		FkTextarea: typeof import('@erp/common')['Textarea'];
		FkTimePicker: typeof import('@erp/common')['TimePicker'];
		FkTimeline: typeof import('@erp/common')['Timeline'];
		FkTimelineItem: typeof import('@erp/common')['TimelineItem'];
		FkTooltip: typeof import('@erp/common')['Tooltip'];
		FkTransfer: typeof import('@erp/common')['Transfer'];
		FkTree: typeof import('@erp/common')['Tree'];
		FkTreeSelect: typeof import('@erp/common')['TreeSelect'];
		FkTrigger: typeof import('@erp/common')['Trigger'];
		FkTypography: typeof import('@erp/common')['Typography'];
		FkTypographyParagraph: typeof import('@erp/common')['TypographyParagraph'];
		FkTypographyTitle: typeof import('@erp/common')['TypographyTitle'];
		FkTypographyText: typeof import('@erp/common')['TypographyText'];
		FkUpload: typeof import('@erp/common')['Upload'];
	}

	export interface ComponentCustomProperties {
		$message: MessageMethod;
		$notification: NotificationMethod;
		$modal: ModalMethod;
		$drawer: DrawerMethod;
	}
}

export {};
