import type { DefaultTheme } from 'vitepress';

const routers: DefaultTheme.SidebarItem[] = [
	{ text: '警告提示 Alert', link: '/components/alert/README.md' },
	// { text: '固钉 Affix', link: '/components/affix/README.md' },
	// { text: '锚点 Anchor', link: '/components/anchor/README.md' },
	{ text: '自动补全 AutoComplete', link: '/components/auto-complete/README.md' },
	// { text: '头像 Avatar', link: '/components/avatar/README.md' },
	// { text: '返回顶部 BackTop', link: '/components/back-top/README.md' },
	// { text: '徽标数 Badge', link: '/components/badge/README.md' },
	// { text: '面包屑 Breadcrumb', link: '/components/breadcrumb/README.md' },
	{ text: '按钮 Button', link: '/components/button/README.md' },
	// { text: '日历 Calendar', link: '/components/calendar/README.md' },
	// { text: '卡片 Card', link: '/components/card/README.md' },
	// { text: '图片轮播 Carousel', link: '/components/carousel/README.md' },
	{ text: '级联选择 Cascader', link: '/components/cascader/README.md' },
	{ text: '复选框 Checkbox', link: '/components/checkbox/README.md' },
	{ text: '折叠面板 Collapse', link: '/components/collapse/README.md' },
	{ text: '颜色选择器 ColorPicker', link: '/components/color-picker/README.md' },
	// { text: '全局配置 ConfigProvider', link: '/components/config-provider/README.md' },
	// { text: '评论 Comment', link: '/components/comment/README.md' },
	{ text: '日期选择器 DatePicker', link: '/components/date-picker/README.md' },
	// { text: '描述列表 Descriptions', link: '/components/descriptions/README.md' },
	// { text: '分割线 Divider', link: '/components/divider/README.md' },
	{ text: '抽屉 Drawer', link: '/components/drawer/README.md' },
	{ text: '下拉菜单 Dropdown', link: '/components/dropdown/README.md' },
	// { text: '空状态 Empty', link: '/components/empty/README.md' },
	{ text: '表单 Form', link: '/components/form/README.md' },
	{ text: '栅格 Grid', link: '/components/grid/README.md' },
	{ text: '图片 Image', link: '/components/image/README.md' },
	{ text: '输入框 Input', link: '/components/input/README.md' },
	{ text: '数字输入框 InputNumber', link: '/components/input-number/README.md' },
	// { text: '标签输入框 InputTag', link: '/components/input-tag/README.md' },
	// { text: '布局 Layout', link: '/components/layout/README.md' },
	// { text: '链接 Link', link: '/components/link/README.md' },
	{ text: '列表 List', link: '/components/list/README.md' },
	// { text: '提及 Mention', link: '/components/mention/README.md' },
	{ text: '菜单 Menu', link: '/components/menu/README.md' },
	{ text: '全局提示 Message', link: '/components/message/README.md' },
	{ text: '对话框 Modal', link: '/components/modal/README.md' },
	// { text: '折叠列表 OverflowList', link: '/components/overflow-list/README.md' },
	{ text: '通知提醒框 Notification', link: '/components/notification/README.md' },
	// { text: '页头 PageHeader', link: '/components/page-header/README.md' },
	{ text: '分页 Pagination', link: '/components/pagination/README.md' },
	{ text: '气泡确认框 Popconfirm', link: '/components/popconfirm/README.md' },
	{ text: '气泡卡片 Popover', link: '/components/popover/README.md' },
	{ text: '进度条 Progress', link: '/components/progress/README.md' },
	{ text: '单选框 Radio', link: '/components/radio/README.md' },
	// { text: '评分 Rate', link: '/components/rate/README.md' },
	// { text: '伸缩框 ResizeBox', link: '/components/resize-box/README.md' },
	// { text: '结果页 Result', link: '/components/result/README.md' },
	{ text: '滚动条 Scrollbar', link: '/components/scrollbar/README.md' },
	{ text: '选择器 Select', link: '/components/select/README.md' },
	// { text: '骨架屏 Skeleton', link: '/components/skeleton/README.md' },
	// { text: '滑动输入条 Slider', link: '/components/slider/README.md' },
	// { text: '间距 Space', link: '/components/space/README.md' },
	{ text: '加载中 Spin', link: '/components/spin/README.md' },
	{ text: '面板分割 Split', link: '/components/split/README.md' },
	// { text: '数值显示 Statistic', link: '/components/statistic/README.md' },
	// { text: '步骤条 Steps', link: '/components/steps/README.md' },
	{ text: '开关 Switch', link: '/components/switch/README.md' },
	{ text: '标签页 Tabs', link: '/components/tabs/README.md' },
	{ text: '标签 Tag', link: '/components/tag/README.md' },
	{ text: '文本域 Textarea', link: '/components/textarea/README.md' },
	{ text: '文字气泡 Tooltip', link: '/components/tooltip/README.md' },
	{ text: '数据穿梭框 Transfer', link: '/components/transfer/README.md' },
	{ text: '树 Tree', link: '/components/tree/README.md' },
	{ text: '树选择 TreeSelect', link: '/components/tree-select/README.md' },
	{ text: '上传 Upload', link: '/components/upload/README.md' },
];
export default routers;
